name: Test Temperature Converter

on: [push, pull_request] # Runs on git push/PR

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Checks out your code
      - run: docker build -t temp-converter-tester .
      - run: docker run --rm temp-converter-tester
