name: Test and Deploy Temperature Converter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Node.js with caching
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      # Install dependencies before Docker build
      - run: npm install

      # Docker operations
      - run: docker build -t temp-converter-tester .
      - run: docker run --rm temp-converter-tester

      # API tests
      - run: npm run test:api

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version

      # Use pinned version of heroku-deploy
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "tempcels"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          healthcheck: "https://tempcels.herokuapp.com/health"
          checkstring: "OK"
          rollbackonhealthcheckfailed: true
